import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Fira_Code, Pixelify_Sans } from "next/font/google";
import Footer from "@/components/Footer";
import "remixicon/fonts/remixicon.css";

const inter = Inter({ subsets: ["latin"] });

const firaCode = Fira_Code({ subsets: ["latin"], variable: "--Fira-Code" });
const pixelifySans = Pixelify_Sans({
  subsets: ["latin"],
  variable: "--Pixelify-Sans",
});

export const metadata: Metadata = {
  title: "Leo's Resume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${firaCode.variable} ${pixelifySans.variable}`}>
        <div className="flex h-screen bg-primary-black justify-center items-center font-firaCode text-base">
          <div className="flex mx-4 w-11/12 h-[96%] bg-primary-dark-blue justify-between items-center rounded-xl border-line border flex-col">
            <Header />
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
